name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-apiserver:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r apiserver/requirements.txt

    - name: Run pytest in ./apiserver
      working-directory: ./apiserver
      run: |
        pytest

  test-puppeteer:
    runs-on: ubuntu-latest
    needs: [] # Runs in parallel with test-apiserver
    
    defaults:
      run:
        working-directory: ./computers/puppeteer

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: computers/puppeteer/package-lock.json

    - name: Install npm dependencies for Puppeteer
      run: npm ci

    - name: Run npm tests for Puppeteer
      run: npm test
